### ISSUE TITLE
Store daily historical power rankings?

### ISSUE THREAD

**Issue by aqsmith08** [lbenz730/NCAA_Hoops#1]
Hey - It looks like your power rankings update daily. Do you store the historical power rankings so that you can see what each team was ranked daily? If so, I'd be interested to comb through that data for the 2017-2018 and 2018-2019 seasons. Would you have that?

**Comment by lbenz730** [comment]
I don't have it daily for the 2017-18 season but I have it for the 2018-19 season https://github.com/lbenz730/NCAA_Hoops/blob/master/3.0_Files/History/history.csv

**Comment by aqsmith08** [comment]
Cool. Thanks for your response. Much appreciated!
